"""Game-content schema for SyllabusSlayer (the roguelike quiz-RPG).

Design (see docs/BUILD-SPEC.md §4): the content is split into two layers.

  1. PEDAGOGICAL layer  -> generated by OpenAI Structured Outputs (these models).
  2. COMBAT / RPG layer  -> computed deterministically by the backend
                            (CombatConfig / EncounterCombat / Reward). The LLM
                            NEVER invents HP/damage/XP numbers.

Generation is staged to stay under Structured Outputs limits
(<=100 properties, <=5 nesting levels):
  * Stage 1 -> CampaignOutline (campaign + acts + encounter stubs, no questions)
  * Stage 2 -> QuestionBatch    (one call per encounter)

All models set ``extra="forbid"`` (-> additionalProperties:false) and every field
is required (optionals are ``X | None``) so they map cleanly onto OpenAI strict
mode. Range/content rules that strict mode does NOT enforce are validated here in
Python (see ``Question`` validator) and mirrored by Zod on the frontend.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, model_validator


class _SOModel(BaseModel):
    """Base model tuned for OpenAI Structured Outputs (strict) compatibility."""

    model_config = ConfigDict(extra="forbid")


# --------------------------------------------------------------------------- #
# Enums
# --------------------------------------------------------------------------- #
class QuestionType(str, Enum):
    multiple_choice = "multiple_choice"
    multi_select = "multi_select"
    true_false = "true_false"
    short_answer = "short_answer"
    ordering = "ordering"
    matching = "matching"


class BloomLevel(str, Enum):
    """Revised Bloom's taxonomy (Anderson & Krathwohl, 2001)."""

    remember = "remember"
    understand = "understand"
    apply = "apply"
    analyze = "analyze"
    evaluate = "evaluate"
    create = "create"


class Difficulty(str, Enum):
    easy = "easy"
    medium = "medium"
    hard = "hard"


class EncounterKind(str, Enum):
    minion = "minion"
    elite = "elite"
    boss = "boss"


class RewardKind(str, Enum):
    relic = "relic"
    powerup = "powerup"
    xp = "xp"
    heal = "heal"


# --------------------------------------------------------------------------- #
# Question building blocks
# --------------------------------------------------------------------------- #
class Option(_SOModel):
    optionId: str
    text: str


class OrderedItem(_SOModel):
    itemId: str
    text: str
    order: int  # the CORRECT 1-based position


class MatchPair(_SOModel):
    pairId: str
    left: str
    right: str  # correct counterpart of ``left``


class Question(_SOModel):
    """Flat, discriminated-union question.

    ``questionType`` is the discriminator. Exactly one per-type cluster is
    non-null; all other clusters are null (strict mode requires every field to
    be present). The post-parse validator enforces that the right cluster is
    populated -- Structured Outputs alone will NOT guarantee this.
    """

    questionId: str
    questionType: QuestionType
    bloomLevel: BloomLevel
    difficulty: Difficulty
    prompt: str

    # --- source grounding (required on every item; powers evals/guardrails) ---
    sourceChunkIds: list[str]
    sourceQuote: str
    sourcePage: int | None

    # --- feedback ---
    explanation: str
    hint: str | None

    # --- per-type clusters (exactly one is non-null per questionType) ---
    options: list[Option] | None  # multiple_choice, multi_select
    correctOptionIds: list[str] | None  # ids into options[]
    correctBoolean: bool | None  # true_false
    acceptedAnswers: list[str] | None  # short_answer
    caseSensitive: bool | None  # short_answer
    orderedItems: list[OrderedItem] | None  # ordering
    matchPairs: list[MatchPair] | None  # matching

    @model_validator(mode="after")
    def _validate_cluster(self) -> "Question":
        qt = self.questionType
        if qt in (QuestionType.multiple_choice, QuestionType.multi_select):
            if not self.options or not self.correctOptionIds:
                raise ValueError(f"{qt} requires non-empty options and correctOptionIds")
            valid_ids = {o.optionId for o in self.options}
            if not set(self.correctOptionIds).issubset(valid_ids):
                raise ValueError("correctOptionIds must reference existing optionIds")
            if qt is QuestionType.multiple_choice and len(self.correctOptionIds) != 1:
                raise ValueError("multiple_choice must have exactly one correct option")
        elif qt is QuestionType.true_false:
            if self.correctBoolean is None:
                raise ValueError("true_false requires correctBoolean")
        elif qt is QuestionType.short_answer:
            if not self.acceptedAnswers:
                raise ValueError("short_answer requires non-empty acceptedAnswers")
        elif qt is QuestionType.ordering:
            if not self.orderedItems:
                raise ValueError("ordering requires non-empty orderedItems")
        elif qt is QuestionType.matching:
            if not self.matchPairs:
                raise ValueError("matching requires non-empty matchPairs")
        return self


# --------------------------------------------------------------------------- #
# Stage 2 output
# --------------------------------------------------------------------------- #
class QuestionBatch(_SOModel):
    encounterId: str
    questions: list[Question]


# --------------------------------------------------------------------------- #
# Stage 1 output (outline)
# --------------------------------------------------------------------------- #
class EncounterStub(_SOModel):
    encounterId: str
    order: int
    kind: EncounterKind
    title: str
    enemyName: str
    enemyFlavor: str
    subTopic: str
    targetQuestionCount: int


class ActStub(_SOModel):
    actId: str
    order: int
    title: str
    syllabusTopic: str
    summary: str
    encounters: list[EncounterStub]


class CampaignOutline(_SOModel):
    schemaVersion: str
    campaignId: str
    title: str
    description: str
    sourceDocumentId: str
    acts: list[ActStub]


# --------------------------------------------------------------------------- #
# Combat / RPG tuning  (computed by the backend, NOT by the LLM)
# --------------------------------------------------------------------------- #
class XpByDifficulty(BaseModel):
    easy: int
    medium: int
    hard: int


class CombatConfig(BaseModel):
    playerStartingHp: int = 100
    baseDamagePerCorrect: int = 10
    streakMultipliers: list[float] = [1.0, 1.25, 1.5, 2.0]
    wrongAnswerHpCost: int = 8
    xpPerCorrectByDifficulty: XpByDifficulty = XpByDifficulty(easy=10, medium=20, hard=35)
    levelXpCurve: list[int] = [0, 100, 250, 450, 700]


class EncounterCombat(BaseModel):
    enemyMaxHp: int
    enemyBaseDamage: int
    kindHpMultiplier: float


class Reward(BaseModel):
    rewardId: str
    kind: RewardKind
    name: str
    description: str
    magnitude: int


SCHEMA_VERSION = "1.0.0"
